# Generated by Django 4.1.5 on 2023-01-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=13)),
                ('price', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('sale_currency', models.CharField(choices=[('Kshs', 'Kenya Shillings'), ('Dollar', 'US Dollars'), ('Euro', 'Euros'), ('Pound', 'Pounds')], default='Kshs', max_length=10)),
                ('sku', models.CharField(default=0, max_length=5)),
            ],
        ),
    ]
