# Generated by Django 4.1.5 on 2023-01-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storecatalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_currency', models.CharField(choices=[('Kshs', 'Kenya Shillings'), ('Dollar', 'US Dollars'), ('Euro', 'Euros'), ('Pound', 'Pounds')], default='Kshs', max_length=10)),
                ('sku', models.CharField(default=0, max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sale_currency',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sku',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storecatalog.author'),
        ),
    ]
