# Generated by Django 4.1.5 on 2023-01-15 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storecatalog', '0002_author_publisher_remove_book_publisher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(help_text='Enter a book genre, e.g., Fantasy', max_length=50)),
                ('publisher_id', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='sale_currency',
            field=models.CharField(choices=[('Kshs', 'Kenya Shillings'), ('Dollar', 'US Dollars'), ('Euro', 'Euros'), ('Pound', 'Pounds')], default='Kshs', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='sku',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storecatalog.genre'),
        ),
    ]
