# Generated by Django 4.1.5 on 2023-01-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storecatalog', '0004_publisher_rename_publisher_id_genre_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
    ]
