# Generated by Django 4.1.5 on 2023-01-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storecatalog', '0005_book_publish_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='storecatalog.publisher'),
        ),
    ]
