# Generated by Django 4.1.5 on 2023-01-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storecatalog', '0006_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
