# Generated by Django 4.1.5 on 2023-01-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storecatalog', '0008_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_summary',
            field=models.CharField(blank=True, help_text='Brief Description of the Genre title', max_length=255),
        ),
    ]
