# Generated by Django 4.1.5 on 2023-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storecatalog', '0009_genre_genre_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='type',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'For Profit'), ('NGO', 'Not For Profit')], default='government', max_length=50, null=True),
        ),
    ]
